import { stdout, stderr } from "node:process";
import { partitionManifests } from "../../domain/service/ManifestParser.js";
import {
  RESERVED_ENTRY_COLUMNS,
  type JsonSchema,
  type ReservedEntryColumn,
} from "../../domain/model/ManifestGrammar.js";
import { loadManifestsFromRoot } from "./loadManifests.js";

/**
 * `mantle emit-types` — generate TypeScript declarations from
 * manifests. Schemas → typed `Entry` data shape; Procedures → typed
 * input/output for handler signatures; Views → typed row shape from
 * the parent Schema's projection.
 *
 * Covers v0.1 JsonSchema features: type:string|integer|number|
 * boolean|object|array|null, properties, required, enum, items,
 * nullable, multi-type unions. Skips $ref / oneOf / anyOf / allOf /
 * if-then-else (none used in v0.1 grammar). Anything unsupported
 * surfaces as `unknown`.
 */
export interface EmitTypesArgs {
  readonly manifests: string;
  readonly namespace: string;
}

export type ParseResult = { kind: "args"; args: EmitTypesArgs } | { kind: "help" };

export function parseArgs(rawArgs: ReadonlyArray<string>): ParseResult {
  let manifests = "./manifests";
  let namespace = "Mantle";
  for (let i = 0; i < rawArgs.length; i++) {
    const a = rawArgs[i];
    if (a === "--manifests") manifests = rawArgs[++i] ?? manifests;
    else if (a === "--namespace") namespace = rawArgs[++i] ?? namespace;
    else if (a === "--help" || a === "-h") return { kind: "help" };
    else if (a !== undefined) {
      throw new Error(`Unknown argument: ${a}`);
    }
  }
  return { kind: "args", args: { manifests, namespace } };
}

function printHelp(): void {
  stdout.write(`mantle emit-types — emit TypeScript .d.ts from manifests

Usage: mantle emit-types [options] > mantle-types.d.ts

Options:
  --manifests <dir>   Manifest root (default: ./manifests)
  --namespace <name>  Top-level namespace (default: Mantle)
  -h, --help          This help

Output: TypeScript declarations on stdout. One namespace contains:
  - Schemas:    interface Entry_<name> { /* data fields */ }
  - Procedures: interface ProcInput_<name> / ProcOutput_<name>
  - Views:      type ViewRow_<name> = projected row shape
`);
}

export async function run(rawArgs: ReadonlyArray<string>): Promise<number> {
  let parsed: ParseResult;
  try {
    parsed = parseArgs(rawArgs);
  } catch (err) {
    stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    return 2;
  }
  if (parsed.kind === "help") {
    printHelp();
    return 0;
  }
  const args = parsed.args;
  const { manifests, parseErrors } = await loadManifestsFromRoot(args.manifests);
  if (parseErrors.some((d) => d.severity === "error")) {
    stderr.write(`Manifest parse errors — run \`mantle validate\` to inspect.\n`);
    return 1;
  }
  const { schemas, procedures, views } = partitionManifests(manifests);
  const schemaByName = new Map(schemas.map((s) => [s.metadata.name, s]));

  const out: string[] = [];
  out.push(`// Generated by \`mantle emit-types\`. Do not edit by hand.`);
  out.push("");
  out.push(`export namespace ${args.namespace} {`);
  out.push("");

  for (const s of schemas) {
    out.push(`  /** Entry data for Schema '${s.metadata.name}' */`);
    out.push(`  export interface Entry_${tsId(s.metadata.name)} ${renderType(s.spec.schema, "  ")}`);
    out.push("");
  }

  for (const p of procedures) {
    out.push(`  /** Procedure '${p.metadata.name}' input */`);
    out.push(`  export interface ProcInput_${tsId(p.metadata.name)} ${renderType(p.spec.input, "  ")}`);
    out.push("");
    out.push(`  /** Procedure '${p.metadata.name}' output */`);
    out.push(`  export interface ProcOutput_${tsId(p.metadata.name)} ${renderType(p.spec.output, "  ")}`);
    out.push("");
  }

  for (const v of views) {
    const parent = schemaByName.get(v.spec.from);
    out.push(`  /** Row shape returned by GET /api/views/${v.metadata.name} */`);
    if (!parent) {
      out.push(`  export type ViewRow_${tsId(v.metadata.name)} = unknown;`);
    } else {
      const props = (parent.spec.schema.properties ?? {}) as Record<string, JsonSchema>;
      const fields = v.spec.fields ?? [...RESERVED_ENTRY_COLUMNS, ...Object.keys(props)];
      const rendered: string[] = [];
      const reservedSet = new Set<string>(RESERVED_ENTRY_COLUMNS);
      for (const f of fields) {
        if (reservedSet.has(f)) {
          rendered.push(`    ${f}: ${RESERVED_COLUMN_TYPES[f as ReservedEntryColumn]};`);
        } else if (props[f]) {
          rendered.push(`    ${f}?: ${renderTypeInline(props[f]!)};`);
        } else {
          rendered.push(`    ${f}?: unknown;`);
        }
      }
      out.push(`  export interface ViewRow_${tsId(v.metadata.name)} {`);
      out.push(...rendered);
      out.push(`  }`);
    }
    out.push("");
  }

  out.push(`}`);

  stdout.write(out.join("\n") + "\n");
  return 0;
}

// Names come from spec's RESERVED_ENTRY_COLUMNS; the TS-type strings
// stay local because they bake in `ContentState` enum values
// (`"draft" | "published" | ...`) — those are also exported from
// spec so a future ContentState change touches both.
const RESERVED_COLUMN_TYPES: Record<ReservedEntryColumn, string> = {
  id: "string",
  status: `"draft" | "published" | "archived"`,
  version: "number",
  createdAt: "number",
  updatedAt: "number",
  authorId: "string | null",
};

function tsId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]+/g, "_");
}

function renderType(schema: JsonSchema, indent: string): string {
  if (schema.type === "object") {
    const props = (schema.properties ?? {}) as Record<string, JsonSchema>;
    const required = new Set(schema.required ?? []);
    const lines: string[] = ["{"];
    for (const [name, sub] of Object.entries(props)) {
      const optional = required.has(name) ? "" : "?";
      lines.push(`${indent}  ${tsKey(name)}${optional}: ${renderTypeInline(sub)};`);
    }
    lines.push(`${indent}}`);
    return lines.join("\n");
  }
  return renderTypeInline(schema);
}

function renderTypeInline(schema: JsonSchema): string {
  const t = schema.type;
  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum
      .map((v) => (typeof v === "string" ? JSON.stringify(v) : String(v)))
      .join(" | ");
  }
  if (Array.isArray(t)) {
    return t.map((kind) => primitiveType(kind, schema)).join(" | ");
  }
  if (t === "object") {
    return renderType(schema, "");
  }
  if (t === "array") {
    const items = schema.items ? renderTypeInline(schema.items) : "unknown";
    return `${items}[]`;
  }
  return primitiveType(typeof t === "string" ? t : "unknown", schema);
}

function primitiveType(t: string, schema: JsonSchema): string {
  switch (t) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return schema.nullable === true ? "unknown | null" : "unknown";
  }
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
